### ISSUE TITLE
get all subscribers for a specific channel

### ISSUE THREAD

**Issue by Deathangel908** [leporo/tornado-redis#90]
How do I get the list of subscribers base on [this](https://github.com/leporo/tornado-redis/blob/master/demos/websockets/app.py) example. I'm looking for something like `c.get_subscribers('channel_name')` If there's no way to get subcribers what Is the best way to store subscribers list? (I'd put them in a global class dictionary)

**Comment by jonashagstedt** [comment]
If you do that, you won't be able to run multiple processes, or load balance your application.

If you have Proc A and Proc B: when a user is added to Proc A it is not visible to Proc B.

You could add a user to Redis when they subscribe and remove the user when they unsubscribe.
You should have some clean-up code that corrects the data periodically as well as it would get out of sync if a process was restarted.

**Comment by Deathangel908** [comment]
You mean to store all users in redis key? like {key : value } = { 'users' : 'Erik' , 'Devid'} just in redis? When a new user logs in he reads the userlist from redis, changes it and saves to redis again, right?
So here's the situation: 

1. User Nick opens a connection and gets value of  'user'  =  'Erik' , 'Devid'. changes it to 'users' = 'Erik', 'Devid', 'Nick'.
2. Before Nick could save just updated userlist to redis a bad guy Dick opens a connection from another proc. Then he reads the userlist from redis and gets: 'Erik' , 'Devid'.
3. Time for Nick to save the userlist. So he saves it to db. Now redis stores 'Erik' , 'Devid', 'Nick'
4. Nick adds his username to 'Erik' , 'Devid' (that he had read before Nick saved it) and puts to redus 'Erik' , 'Devid', 'Dick' overriding Nick's value

**Comment by Deathangel908** [comment]
Thanks, that's what I've been looking for. 
I created redis [hash](http://redis.io/commands#hash), so when user logs in I  [add](http://redis.io/commands/hset) `{ id(connection) : username}` to redis.

**Comment by jonashagstedt** [comment]
Remember that there can be instances when this will give you the wrong information.
Imagine a scenario where Redis goes down just as the user disconnects, or if you are debugging things etc.
